export const products = [
  { id: 1, name: "Яблоко", price: 100, oldPrice: 120, image: "🍎" },
  { id: 2, name: "Банан", price: 80, oldPrice: 100, image: "🍌" },
  { id: 3, name: "Апельсин", price: 90, oldPrice: 110, image: "🍊" },
  { id: 4, name: "Ананас", price: 150, oldPrice: 170, image: "🍍" },
  { id: 5, name: "Клубника", price: 200, oldPrice: 230, image: "🍓" },
  { id: 6, name: "Виноград", price: 130, oldPrice: 150, image: "🍇" },
  { id: 7, name: "Груша", price: 110, oldPrice: 130, image: "🍐" },
  { id: 8, name: "Арбуз", price: 180, oldPrice: 200, image: "🍉" },
  { id: 9, name: "Лимон", price: 70, oldPrice: 90, image: "🍋" },
  { id: 10, name: "Киви", price: 120, oldPrice: 140, image: "🥝" },
  { id: 11, name: "Персик", price: 140, oldPrice: 160, image: "🍑" },
  { id: 12, name: "Черника", price: 220, oldPrice: 240, image: "🌹" },
  { id: 13, name: "Манго", price: 160, oldPrice: 180, image: "🥭" },
  { id: 14, name: "Кокос", price: 190, oldPrice: 210, image: "🥥" },
  { id: 15, name: "Помидор", price: 60, oldPrice: 80, image: "🍅" },
  { id: 16, name: "Морковь", price: 50, oldPrice: 70, image: "🥕" },
  { id: 17, name: "Огурец", price: 40, oldPrice: 60, image: "🥒" },
  { id: 18, name: "Картофель", price: 30, oldPrice: 50, image: "🥔" },
  { id: 19, name: "Баклажан", price: 90, oldPrice: 110, image: "🍆" },
  { id: 20, name: "Перец", price: 100, oldPrice: 120, image: "🌶️" },
];
